### ISSUE TITLE
"Unrecognized import path" Error

### ISSUE THREAD

**Issue by ArpitKubadia** [KathanP19/Gxss#1]
When trying `go get -u github.com/KathanP19/Gxss`, I am getting the following trace:

> unrecognized import path "bufio": import path does not begin with hostname
unrecognized import path "crypto/tls": import path does not begin with hostname
unrecognized import path "flag": import path does not begin with hostname
unrecognized import path "fmt": import path does not begin with hostname
unrecognized import path "errors": import path does not begin with hostname
unrecognized import path "bytes": import path does not begin with hostname
unrecognized import path "encoding/binary": import path does not begin with hostname
unrecognized import path "net": import path does not begin with hostname
unrecognized import path "runtime": import path does not begin with hostname
unrecognized import path "sort": import path does not begin with hostname
unrecognized import path "strings": import path does not begin with hostname
unrecognized import path "sync": import path does not begin with hostname
unrecognized import path "syscall": import path does not begin with hostname
unrecognized import path "time": import path does not begin with hostname
unrecognized import path "unsafe": import path does not begin with hostname
unrecognized import path "io": import path does not begin with hostname
unrecognized import path "os": import path does not begin with hostname
unrecognized import path "strconv": import path does not begin with hostname
unrecognized import path "unicode/utf8": import path does not begin with hostname
unrecognized import path "io/ioutil": import path does not begin with hostname
unrecognized import path "net/http": import path does not begin with hostname
unrecognized import path "net/url": import path does not begin with hostname
unrecognized import path "regexp": import path does not begin with hostname

**Comment by KathanP19** [comment]
Please update the golang to latest version try again.

**Comment by ArpitKubadia** [comment]
I am on `go version go1.14.7 `
On which version have you tested it?

**Comment by KathanP19** [comment]
1.15

**Comment by KathanP19** [comment]
Closing the issue , updating go will fix it
