### ISSUE TITLE
Proxy options?

### ISSUE THREAD

**Issue by alfonsocaponi** [KathanP19/Gxss#11]
How can I use it with a http proxy?

Thank you very much

**Comment by alfonsocaponi** [comment]
Is it possibile enable os proxy support? :(

**Comment by Phoenix-721** [comment]
I'm unable to use Gxss in Kali terminal.
 
Error shown:-

└─$ cat files.txt | gxss                                                                                                                                                                1 
Command 'gxss' not found
Try: sudo apt install <deb name>


Why is this happening ? Can someone help?

**Comment by Phoenix-721** [comment]
I'm unable to use Gxss in Kali terminal.

Error shown:-
![Gxss](https://user-images.githubusercontent.com/75171792/123687296-6193a400-d86e-11eb-98e5-7a5d789ebce4.png)

 
Gxss : Command not found


Why is this happening ? Can someone help?

**Comment by KathanP19** [comment]
@Phoenix-721 please check if golang is installed properly or not and the path is set properly, also alternatively you can use binary built.

**Comment by noblevk21** [comment]
After downloading binaries and extracting it.
Give following command and check whether Gxxs is working
`./Gxss -v`
or
`sudo ./Gxss -v` 

This has worked for me perfectly

**Comment by KathanP19** [comment]
It been added and is in development will be released soon

**Comment by abdulx01** [comment]
> I'm unable to use Gxss in Kali terminal.
> 
> Error shown:- ![Gxss](https://user-images.githubusercontent.com/75171792/123687296-6193a400-d86e-11eb-98e5-7a5d789ebce4.png)
> 
> Gxss : Command not found
> 
> Why is this happening ? Can someone help?

Same Problem with me Even I have installed golang properly but still found this error: Gxss: Command not found :(

**Comment by dhanushkkarh** [comment]
I'm facing the same problem. What is that??

My whatsapp is: +916380552921
mail: dhanushkkarh@gmail.com

**Comment by dhanushkkarh** [comment]
> I'm unable to use Gxss in Kali terminal.
> 
> Error shown:- ![Gxss](https://user-images.githubusercontent.com/75171792/123687296-6193a400-d86e-11eb-98e5-7a5d789ebce4.png)
> 
> Gxss : Command not found
> 
> Why is this happening ? Can someone help?
I'm facing the same problem. What is that??

My whatsapp is: +916380552921
mail: dhanushkkarh@gmail.com

**Comment by abdulx01** [comment]
Hy, I solved this problem. Simply you can move to /usr/bin your Gxss tool.
