### ISSUE TITLE
request hangup, no timout handleing

### ISSUE THREAD

**Issue by ranjit-git** [KathanP19/Gxss#12]
your tool will hangup for bellow scenario , no request timeout handleing here

setup a netcat server --> nc -lnvp 8182
run  echo "http://localhost:8182/" |Gxss -p test

**Comment by KathanP19** [comment]
Hey Ranjit, 
I was not able to reproduce this issue, I followed the steps exactly as you told me, it seems it's only an issue from your side kindly check again after updating

**Comment by KathanP19** [comment]
closing this.
