### ISSUE TITLE
No result back when use Huge list of Endpoint's 

### ISSUE THREAD

**Issue by Deku-izuku-dotcom** [KathanP19/Gxss#13]
Hello @KathanP19  

I Instal your tool work will & even better that kxss in the output , but it seem that when I feed them a Huge list of endpoint he didn't return anything for about 3 hours ( VPS ) . can you please check the problem ? 

Thanks a lot

**Comment by KathanP19** [comment]
Hey @Deku-izuku-dotcom ,
Can you check if there is any link that has reflecting value in it, and also try increasing the concurrency using the option `-c`

**Comment by Deku-izuku-dotcom** [comment]
After increasing the concurrency , the tool Works , it seem that a simple Connection issue from my device , sorry for that.
