### ISSUE TITLE
package moul.io/http2curl: unrecognized import path "moul.io/http2curl": 

### ISSUE THREAD

**Issue by KingOfBugbounty** [KathanP19/Gxss#14]
package moul.io/http2curl: unrecognized import path "moul.io/http2curl": https fetch: Get "https://moul.io/http2curl?go-get=1": dial tcp 162.243.166.170:443: i/o timeout

:/

**Comment by KathanP19** [comment]
I checked it on my system as well as on fresh VPS its working fine, can you check again

**Comment by KingOfBugbounty** [comment]
continue error :/ https://ibb.co/LJWXQTK

**Comment by KathanP19** [comment]
Try this `export GOPROXY=https://proxy.golang.org` and try again or else use a pre-built binary file from https://github.com/KathanP19/Gxss/releases here.

**Comment by KathanP19** [comment]
let me know if that solves the issue

**Comment by KathanP19** [comment]
Its should be fixed by now try again
