### ISSUE TITLE
Small question about the -p flag 

### ISSUE THREAD

**Issue by spazbg** [KathanP19/Gxss#2]
If I don't provide "-p Payload" dose the tool have a default one?

**Comment by KathanP19** [comment]
try it yourself

**Comment by spazbg** [comment]
Sorry, my mistake, I am playing with the tool now and I can see how is working. I was thinking that by -p payload you must provide something like "><script>alert(1)</script> and it wasn't working for me on a test page where I now this payload is working... I can see what is the idea now :)
