### ISSUE TITLE
some cases cant find reflect param

### ISSUE THREAD

**Issue by ranjit-git** [KathanP19/Gxss#4]
bellow url cant find reflected param

Payload
==========
echo -e -n "http://araliyagardens-hotel.com/booking.php?id=xss"|./Gxss -p "xss" -c 10

**Comment by KathanP19** [comment]
I checked the issue and found that its waf which is blocking gxss, while if you open the URL in a browser it works fine, I think I need to add User-Agent Option. Thank you.

**Comment by KathanP19** [comment]
Fixed the issue try again
