### ISSUE TITLE
PANIC: invalid URL escape

### ISSUE THREAD

**Issue by uBadRequest** [KathanP19/Gxss#6]
panic: invalid URL escape "%n-"

goroutine 253 [running]:
main.testxss(0x7ffde745283b, 0x7, 0x0)
        /root/go/src/github.com/KathanP19/Gxss/gxss.go:100 +0x9c6
main.main.func1(0xc000190c20, 0xc0001ac3b0, 0xc000015010)
        /root/go/src/github.com/KathanP19/Gxss/gxss.go:68 +0x45
created by main.main
        /root/go/src/github.com/KathanP19/Gxss/gxss.go:67 +0x331

**Comment by KathanP19** [comment]
Can you check if you are using the latest version.

**Comment by uBadRequest** [comment]
Yeah I just installed it

**Comment by KathanP19** [comment]
Seems because "%n-" was a bad request remove that particular URL from the list and try

**Comment by KathanP19** [comment]
Fixed the issue Please check with major update
