### ISSUE TITLE
in this url cant find reflect param

### ISSUE THREAD

**Issue by hamedeasy** [KathanP19/Gxss#7]
plz check this
echo "https://thaidocs.com/terms/?open=ggggggg" | Gxss -c 100 -p XXss
\ Testing XSS

**Comment by KathanP19** [comment]
Thank you for the issue, I will look into this issue

**Comment by KathanP19** [comment]
I check the command you shared and I didn't found any issue, it's working perfectly fine.
```
echo "https://thaidocs.com/terms/?open=ggggggg" | Gxss -c 100 -p XXss
| Testing XSS  URL: "https://thaidocs.com/terms/?open=XXss"
Reflected Param : "open"
\ Testing XSS 
```

**Comment by KathanP19** [comment]
Update and try again, if not working, you can reopen this issue
